function plotpayload2(beam)
    %rectangular prism
    %need width(w),height(h),length(l) in meters
    w = beam(1);h = beam(2);l = beam(3);

    %face 2
    l_start = 0;l_end = l;
    w_start = 0;w_end = w; 
    h_start = 0;h_end = h;
    vert = [l_start w_start h_start;...
            l_end w_start h_start;...
            l_end w_end h_start;...
            l_start w_end h_start;...
            l_start w_start h_end;...
            l_end w_start h_end;...
            l_end w_end h_end;...
            l_start w_end h_end;...
            ];
    fac = [1 2 6 5;2 3 7 6;3 4 8 7;4 1 5 8;1 2 3 4;5 6 7 8]; 
    patch('Vertices',vert,'Faces',fac,'FaceVertexCData',hsv(6),'FaceColor','w','FaceAlpha','0.3')
    view(3)
hold on 
end